# Path to your oh-my-bash installation.
export OSH=$HOME/.oh-my-bash

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-bash is loaded.
OSH_THEME="purity"

completions=(
  git
  composer
  ssh
)

aliases=(
  general
)

plugins=(
  git
  bashmarks
)

source $OSH/oh-my-bash.sh

# Vim for life
export EDITOR=vim

ENABLE_CORRECTION="true"
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Overcoming Muscle Memory
if type nvim >/dev/null 2>&1; then
  alias vim='nvim'
fi


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

export PATH="$(yarn global bin):$PATH"

# FUNCTIONS

function mkcd () {
  case "$1" in
    */..|*/../) cd -- "$1";; # that doesn't make any sense unless the directory already exists
    /*/../*) (cd "${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd -- "$1";;
    /*) mkdir -p "$1" && cd "$1";;
    */../*) (cd "./${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd "./$1";;
    ../*) (cd .. && mkdir -p "${1#.}") && cd "$1";;
    *) mkdir -p "./$1" && cd "./$1";;
  esac
}

alias md="mkcd"

function please() {
  local CMD=$(history -1 | cut -d" " -f4-)
  sudo "$CMD"
}

function weather() {
  curl 'wttr.in/~'${1:-Parbatsar}'+'$2'?'${3:-0}
}

alias m="weather"

shorten() { node ~/code/pika.im/node_modules/.bin/netlify-shortener "$1" "$2"; }
killport() { lsof -i tcp:"$*" | awk 'NR!=1 {print $2}' | xargs kill -9; }

fig() { figlet "$@" | lolcat; }
tm() { toilet -f mono12 "$@" | lolcat; }
tf() { toilet -f future "$@" | lolcat; }
tb() { toilet -f bigmono12 "$@" | lolcat; }

function ranger-cd() {
  tempfile="$(mktemp -t tmp.XXXXXX)"
  ranger --choosedir="$tempfile" "${@:-$(pwd)}"
  test -f "$tempfile" &&
    if [ "$(cat -- "$tempfile")" != "$(echo -n $(pwd))" ]; then
      cd -- "$(cat "$tempfile")"
    fi
  rm -f -- "$tempfile"
}

gccd() {
  git clone "$1" && cd "$(basename "$1" .git)"
}

# ALIASES

alias c="coding $HOME/Code"

alias v="nvim"
alias vim="nvim"
alias n="npm"
alias r="ranger"

alias pls=please

alias mk=make
alias mkc="make clean"
alias mkr="make run"
alias mkt="make test"

# terminal rickroll 🕺💃
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'
alias t="touch"

alias v=vim
alias vi=vim

alias c="code"
alias cr="code -r"
alias cr.="code -r ."

alias r=ranger-cd
alias vm="vifm ."

alias ru=ruby
alias n="node"

alias python="python3"
alias p="python3"
alias pip="pip3"
alias pi="pip3"
alias ve="virtualenv"

# Changing "ls" to "exa"
alias l='exa --color=always --group-directories-first'      # some files and dirs
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -1 --color=always --group-directories-first'  # long format
alias ls='exa -a1 --color=always --group-directories-first' # my preferred listing

alias cp="cp -i" # confirm before overwriting something
alias df='df -h' # human-readable sizes
alias grep='grep --colour=auto'

alias pg="echo 'Pinging Google' && ping www.google.com"

alias vz="vim ~/.zshrc"
alias vza="vim ~/dotfiles/zsh/aliases.zsh"
alias vzp="vim ~/dotfiles/zsh/plugins.zsh"
alias vzf="vim ~/dotfiles/zsh/functions.zsh"
alias vn="vim ~/.config/nvim/init.vim"
alias vr="vim ~/.config/ranger/rc.conf"

alias ni="npm install"
alias nrs="npm run start -s --"
alias nrb="npm run build -s --"
alias nrd="npm run dev -s --"
alias nrt="npm run test -s --"
alias nrtw="npm run test:watch -s --"
alias nrv="npm run validate -s --"
alias rmn="rm -rf node_modules"
alias flush-npm="rm -rf node_modules && npm i && say NPM is done"
alias nicache="npm install --prefer-offline"
alias nioff="npm install --offline"

alias d='ddgr'
alias wi="wikit"
alias lc="lolcat"
alias iu="imgur-uploader"

# Easier directory navigation.
alias ~="cd ~"
alias .="cd .."
alias ..="cd ../.."
alias ...="cd ../../.."
alias ....="cd ../../../.."

# Docker
alias d="docker"
alias dr="docker run"
alias drrm="docker run --rm"
alias drit="docker run -it"
alias dritrm="docker run -it --rm"
alias dritirm="docker run -it --init --rm"
alias dritrmn="docker run -it --rm --name"
alias dc="docker container"
alias ds="docker start"
alias dl="docker logs"
alias dsa="docker start -a"
alias dps="docker ps"
alias dpsa="docker ps --all"
alias dst="docker stop"
alias dk="docker kill"
alias dsp="docker system prune"
alias deit="docker exec -it"
alias db="docker build"
alias dcc="docker commit -c"
alias de="docker exec"
alias dbt="docker build --tag"
alias dcp="docker container prune"
alias dils="docker image ls"

# Git
alias git="hub"
alias gs="git status"
alias gc="git clone"
alias agi="add-gitignore"

# Heroku
alias gphm="git push heroku master"

# Yarn
alias ys="yarn server"
alias ysr="yarn server"
alias yd="yarn dev"

# Scrot
alias s="scrot"

# Youtube DL
alias ydl="youtube-dl"
alias ydlb="youtube-dl -f bestvideo+bestaudio"
alias ydlbd="youtube-dl -f bestvideo+bestaudio -ci --batch-file=download.txt"
alias ydd="youtube-dl -f bestvideo+bestaudio -ci --batch-file=download.txt"

alias postgres="sudo -u postgres"
alias pg="sudo -u postgres"

alias todo="vim ~/.todo.txt"

alias y="yarn"
alias ya="yarn add"
alias yad="yarn add --dev"
alias yga="yarn global add"
alias yst="yarn start"
alias yt="yarn test"
alias yb="yarn build"
